# airflow/docker-compose.yml
services:
  airflow-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata_airflow:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 duckdb==1.0.0 requests==2.32.3 httpx==0.27.2
        beautifulsoup4==4.12.3 lxml==5.2.2 tenacity==8.5.0 PyYAML==6.0.2
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate &&
          airflow users create
            --role Admin
            --username $$ _AIRFLOW_WWW_USER_USERNAME
            --password $$ _AIRFLOW_WWW_USER_PASSWORD
            --firstname Admin --lastname User --email admin@example.com || true"
    volumes:
      - ../:/opt/airflow/project       # monta todo tu repo
      - ./dags:/opt/airflow/dags

  airflow-webserver:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 duckdb==1.0.0 requests==2.32.3 httpx==0.27.2
        beautifulsoup4==4.12.3 lxml==5.2.2 tenacity==8.5.0 PyYAML==6.0.2
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ../:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  airflow-scheduler:
    image: apache/airflow:2.9.3-python3.11
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PIP_ADDITIONAL_REQUIREMENTS: >
        pandas==2.2.2 duckdb==1.0.0 requests==2.32.3 httpx==0.27.2
        beautifulsoup4==4.12.3 lxml==5.2.2 tenacity==8.5.0 PyYAML==6.0.2
    command: scheduler
    volumes:
      - ../:/opt/airflow/project
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

volumes:
  pgdata_airflow:
